---
# tasks file for haproxy

- name: "Install Haproxy"
  package:
      name: "haproxy"
      state: present
  register: haproxy_install
  
- name: "Copy template haproxy config file"
  template:
      src: "haproxy.cfg.j2"
      dest: "/etc/haproxy/haproxy.cfg"
  notify: "Restart haproxy"
