- hosts: aws_loadbalancer
  vars_files:
  - loadbalancer/vars.yml
  - webservers/vars.yml
 
  become: true
  tasks:
  
  - name: "Install Haproxy"
    package:
       name: "haproxy"
       state: present
    register: haproxy_install
  
  - name: "Copy template haproxy config file"
    template:
       src: "loadbalancer/haproxy.cfg.j2"
       dest: "/etc/haproxy/haproxy.cfg"
    notify: "Restart haproxy"
 
  handlers:
  - name:  "Restart haproxy"
    service:
       name: "haproxy"
       state: restarted


