- hosts: all
  tasks:
    - package:
        name: "httpd"
        state: present
    
    - copy:
        src: "/root/Desktop/playbook_dir/mywebsite/"
        dest: "/var/www/html/"
    
    - service:
        name: "httpd"
        state: started
    
    - firewalld:
        port: "80/tcp"
        permanent: yes
        state: enabled
        immediate: yes    
