- hosts: localhost
  become: true
  tasks:
  - debug:
      var: ansible_os_family
      
  - name: "create yum repository for docker"
    yum_repository:
      name: docker-repo
      description: "repo for docker"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes
      gpgcheck: no
    when: ansible_facts['os_family'] == 'RedHat'
  
  - name: "Install docker"
    package: 
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "Install pip"
    package: 
      name: "python3-pip"
      state: present
      update_cache: true
    
  - name: "Install docker sdk"
    pip:
     name: "docker"
 
  # - name: "Update docker service"
  #   replace:
  #      path: "/lib/systemd/system/docker.service"
  #      regexp: "^ExecStart.*"
  #      replace: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243"
  #   notify: 
  #   - "Restart docker"
  #   - "Reload deamon"
  
  - name: "Start docker service"
    service:
      name: "docker"
      state: started


  # handlers:
  # - name: "Restart docker"
  #   service:
  #      name: "docker"
  #      state: restarted

  # - name: "Reload deamon"
  #   systemd:
  #      daemon_reload: yes

