---
# defaults file for myapache

ap_extra_software:
- python3
- git

ap_http_host_dir: "creators_by_heart"
ap_http_conf_file: creators_by_heart_dev.conf
ap_disable_default: true
ap_http_port: "8080"

ap_source_code_location: 'files/source_code/'