FROM ubuntu:latest

RUN apt-get update
RUN apt-get install ssh -y

RUN useradd -m -N -s /bin/bash -u 1000 -p 'ubuntu' ubuntu && \
    usermod -aG sudo ubuntu


EXPOSE 22

USER ubuntu

CMD service ssh start
